# Generated by Django 4.0.2 on 2022-06-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Hamburguesa', 'Hamburguesa'), ('Perro', 'Perro'), ('Pollo', 'Pollo'), ('Papa', 'Papas'), ('Postre', 'Postre'), ('Combo', 'Combo'), ('Acompanante', 'Acompanante')], default='Hamburguesa', max_length=11),
        ),
    ]
