# Generated by Django 4.0.2 on 2022-06-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='celular',
            field=models.IntegerField(null=True),
        ),
    ]
