# Generated by Django 4.0.2 on 2022-06-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_orden_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='valoracion',
            field=models.IntegerField(default=0),
        ),
    ]
